on:
  push:
    branches:
      - none

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        with:
          TARGET: https://docs.mapsindoors.com
          EXCLUDED_KEYWORDS: nuget, openid
          RECURSIVE: true
          RATE_LIMIT: 0
