name: CHANGELOG

on:
  push:
    paths:
      - 'src/changelogs/web/CHANGELOG.md'
      - 'src/changelogs/components/CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
